#!/usr/bin/bash
set -euo pipefail

echo "Extracting N4O Terminologies from BARTOC"

#
# distributions: [{{
#   format: "http://format.gbv.de/jskos",
#   download: "https://api.dante.gbv.de/export/download/kenom_material/default/kenom_material__default.jskos.ndjson"
#  },{} # TODO RDF download

curl -s 'https://bartoc.org/api/voc?partOf=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F18961&limit=500' \
    > terminologies.json

# BARTOC does not contain all Information from DANTE API, so we just add some download URLs
# jq 'map(if ((.identifier//[])[]|startswith("http://uri.gbv.de/terminology/kenom")) then (.+{x:1}) else . end)' \

jq -r '"got \(length) terminologies"' terminologies.json

npm run --silent jsonld2rdf -- -c jskos-context.json terminologies.json > terminologies.nt
wc -l terminologies.nt

