#!/usr/bin/bash
set -euo pipefail
function error() { echo $@ >&2; exit 1; }

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 DOI|URL"
    echo "Load Data from Zenodo publication, given by DOI"
    exit
fi

id=$1
if [[ "$id" =~ ^https://zenodo\.org/records/[0-9]+$ ]]; then
  id="${id##*/}"
elif [[ "$id" =~ ^https://doi\.org/10\.5281/zenodo\.[0-9]+$ ]]; then
  id="${id##*/}"
else
  error "Expecting Zenodo DOI or record URL"
fi

doi=https://doi.org/10.5281/zenodo.$id
mkdir -p inbox/zenodo-$id/
cd inbox/zenodo-$id/

# TODO: Zenodo does not have last-modified header (?!)
echo "Downloading $doi"
wget -nv -N "https://zenodo.org/api/records/$id/files-archive"

echo "Extracting $doi"
unzip files-archive

# TODO: generate datapackage
# fido -zip files-archive -nomatchprintf "" -matchprintf "%(info.filesize)s,%(info.mimetype)s,%(info.filename)s\n"
