#!/usr/bin/bash
set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Usage: $0 <graph> <file>"
    echo "Import an RDF file into Fuseki graph. Existing graph is overridden."
    exit 1
fi

graph=$1
file=$2

if [[ -f "$file" ]]; then
    echo "Importing $file into Fuseki graph $graph"
    /opt/fuseki/bin/s-put http://localhost:3030/n4o-rdf-import $graph $file
else
    echo "Missing RDF file: $file"
    exit 1
fi
