#!/usr/bin/bash
set -euo pipefail

n4oc=https://graph.nfdi4objects.net/collection/

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 COLLECTION_ID|all|sources"
  echo "Imports into local Fuseki store"
  exit
fi

function import_collection() {
    collection=$1
    if [[ ! "$collection" =~ ^[0-9]*$ ]]; then
        echo "Collection ID must be numeric!"
        exit 1
    fi
    ./load-rdf-graph "$n4oc$collection" "import/$collection/filtered.nt"
}

if [[ "$1" = "sources" ]]; then
    import_file "sources/n4o-sources.nt" "$n4oc"
elif [[ "$1" = "all" ]]; then
    for collection in import/*; do
        import_collection $(basename $collection)
    done
else
    import_collection $1
fi
