#!/usr/bin/bash
set -euo pipefail
function error() { echo $@ >&2; exit 1; }

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 COLLECTION_ID|all"
    echo "Imports into local Fuseki store"
    exit
fi

function import_collection() {
    collection=$1
    [[ "$collection" =~ ^[0-9]*$ ]] || error "Collection ID must be numeric!"
    uri=https://graph.nfdi4objects.net/collection/$collection

    ./load-rdf-metadata $collection --issued
    ./load-rdf-graph $uri import/$collection/filtered.nt
}

if [[ "$1" = "all" ]]; then
    for collection in import/*; do
        import_collection $(basename $collection)
    done
else
    import_collection $1
fi
