#!/usr/bin/bash
set -euo pipefail

function usage() {
    echo "Usage: $0 COLLECTION_ID [--issued]"
    echo "Update description about a collection in Fuseki."
    echo "Option --issued updates dct:issued with current timestamp."
    exit
}

issued=${2:-}

[[ "${1:-}" =~ ^[0-9]*$ ]] || usage
[[ $# -le 2 ]] || usage
[[ $# -eq 2 ]] && [[ "$issued" != "--issued" ]] && usage

function error() {
    echo $@ >&2
    exit 1
}

id=$1
uri=https://graph.nfdi4objects.net/collection/$id
collections=collections.json
about=$(jq --arg id $uri '.[]|select(.id==$id)' $collections \
    | npm run --silent -- jsonld2rdf -c sources/context.json)
[[ -z "$about" ]] && error "Missing $uri in $collections"

filter="FILTER (?p != dct:issued)"
[[ -z "$issued" ]] || filter="" 

echo "Deleting metadata of $uri"
sparql=$(cat <<-SPARQL
PREFIX n4oc: <https://graph.nfdi4objects.net/collection/>
PREFIX dct: <http://purl.org/dc/terms/>
WITH n4oc:
DELETE { ?s ?p ?o }
WHERE {
  { VALUES ?s { n4oc:$id } ?s ?p ?o }
  UNION
  { VALUES ?o { n4oc:$id } ?s ?p ?o } 
  $filter
}
SPARQL
)

# echo "$sparql"
./update-rdf "$sparql"

[[ ! -z "$issued" ]] && issued="<$uri> dct:issued \"$(date -Iminutes)\"^^xsd:dateTime ."
    
echo "Adding new metadata of $uri"
sparql=$(cat <<-SPARQL
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
INSERT DATA { GRAPH <https://graph.nfdi4objects.net/collection/> {
$about
<$uri> skos:notation "$id" .
$issued
} }
SPARQL
)

# echo "$sparql"
./update-rdf "$sparql"

