#!/usr/bin/bash
set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Usage: $0 SPARQL"
    echo "Execute arbitrary SPARQL Update query."
    exit 1
fi

# SPARQL Update API
api=http://localhost:3030/n4o-rdf-import/update

curl -X POST "$api" --header "Content-Type: application/sparql-update" --data-binary "$1"
